logging:
  level:
#    edu.javial.cert.se.core.threading: DEBUG
    edu:
      javial:
        cert:
          se: DEBUG

#  #  file: debugLogs/dev_app.log
  pattern:
    console: "%date{HH:mm:ss.SSS} [%thread] | %logger{10}.%method.%L : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n || %logger{10}.%method.%L"
#
#    org.springframework.web: INFO