spring:
  application:
    name: certifySpringDataRest
  data:
    rest:
      base-path: /api
  profiles:
    active: dev
    include: h2Conventional
  h2:
    console:
      enabled: false
      path: /h2
name: dev2-YAML
debug:
  false

server:
  port: 8085
#  port: 0 # random port


#spring.data.rest.basePath=/api

#---------------------------------
logging:
  level:
    org.springframework.web: INFO
    com.category.fans: DEBUG
  file: /dev/null
  pattern:
    console: "%date{HH:mm:ss.SSS} [%thread] | %logger{10}.%method.%L : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n || %logger{10}.%method.%L"
