micronaut:
  application:
    name: hello-world
endpoints:
    loggers:
      enabled: true
      sensitive: true
#  info:
#    enabled: true
#    sensitive: true
#  health:
#    enabled: true
#    sensitive: true
#    details-visible: ANONYMOUS
#    status:
#      http-mapping:
#        UP: 503


