#app:
#  team:XYZ Team
#  team-size:3
#  team-leader:Mahesh
#  employees:
#    - name:Amar
#      designation:Developer
#      age:25
#    - name:Akbar
#      designation:Tester
#      age:23
#    - name:Anthony
#      designation:Designer
#      age:27
#  technologies:
#    BACKEND:Java
#    FRONTEND:Angular
#    DATABASE:Oracle
#  clients:
#    - A Client
#    - B Client
#    - C Client
#  company:
#    name:ABC Ltd
#    ceo:Narendra
#    location:Delhi
#project:
#  project-name:PQR Project
#  size:10
#  manager:John

app:
  currencyUrl: "http://data.fixer.io/api/latest?access_key=3e71e8caaa61c017d627f66461436b5f&symbols=USD"

logging:
  level:
    org.springframework.web: INFO
    sci:
      spring:
        rest:
          template:
            maps: DEBUG
#  #  file: debugLogs/dev_app.log
#  pattern:
#    console: "%date{HH:mm:ss.SSS} [%thread] | %logger{10}.%method.%L : %msg%n"
##    file: "%d %-5level [%thread] %logger : %msg%n || %logger{10}.%method.%L"